### ISSUE TITLE
请问是如何处理导航栏和微信自带胶囊的对齐问题？

### ISSUE THREAD

**Issue by WuHuaJi0** [wahao/wepy-com-inaver#1]
我这边测试，好像不同的机型，胶囊的位置不一样呢？ 能指点一下么

**Comment by WuHuaJi0** [comment]
好吧，试了一下你这个，没有对齐，这块坑好多

**Comment by dtboy1995** [comment]
可能得多机型适配了，就算通过systeminfo拿手机状态栏高度，这块微信本身也是坑，胶囊本身在Android和ios的上边距还不一致呢，@WuHuaJi0，您这边有新的方法可以分享一下。看作者的代码是写死了44个rpx

**Comment by WuHuaJi0** [comment]
@dtboy1995 好像就是44rpx ，我已经有段时间没做小程序了，有点记不得了

**Comment by dtboy1995** [comment]
@WuHuaJi0，谢谢回复，我也不知道，多测几台机器就好了
